### ISSUE TITLE
Setting "Index" parameter in PgJSON causes requests to fail

### ISSUE THREAD

**Issue by maxbes** [LemonLDAPNG/Apache-Session-Browseable#34]
If a user accidentally sets the "Index" parameter when using PgJSON, session creation fails with (eg)

```
[error] Session cannot be tied: DBD::Pg::st execute failed: ERROR: column "_whattotrace" of relation "sessions" does not exist
```
The reason is that PgJSON declares its store to be `Apache::Session::Browseable::Store::Postgres` which uses the "Index" option

It should probably use `Apache::Session::Store::Postgres` instead, so that the "Index" option won't interfere

Low priority issue, this only causes problems in a configuration that is wrong to begin with

**Comment by guimard** [comment]
Wrong: backend just enables UTF8. No issue here, just a wrong config :wink:
